# SET UP

**IMPORTANTE**: Recuerda hacer una copia de esta plantilla para no machacar la original.

## CREAR EL ENTORNO PARA EL PROYECTO

Prediccion tiempo ohio.  
Data source: https://www.ncei.noaa.gov/access

## IMPORTAR PAQUETES

In [6]:
import os
import numpy as np
import pandas as pd

#Automcompletar r√°pido
%config IPCompleter.greedy=True

## CREAR EL DIRECTORIO DEL PROYECTO

### Definir el directorio raiz donde vamos a crear el proyecto

In [1]:
raiz = 'C:/proyectos/weather_ohio/'

## CREAR LOS DATASETS INICIALES

Poner los datos originales en la carpeta '/02_Datos/01_Originales'

### Importar los datos

Sustituir el nombre_fichero_datos.

In [2]:
nombre_fichero_datos = 'ohio_weather.csv'

Cargar los datos.

In [7]:
ruta_completa = raiz + '/02_Datos/01_Originales/' + nombre_fichero_datos
print(ruta_completa)
datos = pd.read_csv(ruta_completa,index_col=0)
datos

C:/proyectos/weather_ohio//02_Datos/01_Originales/ohio_weather.csv

,NAME,LATITUDE,LONGITUDE,ELEVATION,DATE,AWND,AWND_ATTRIBUTES,FMTM,FMTM_ATTRIBUTES,PGTM,...,WT02,WT02_ATTRIBUTES,WT03,WT03_ATTRIBUTES,WT06,WT06_ATTRIBUTES,WT08,WT08_ATTRIBUTES,WT09,WT09_ATTRIBUTES
STATION,,,,,,,,,,,,,,,,,,,,,
USW00014894,"WHEELING OHIO CO AIRPORT, WV US",40.16994,-80.64406,364.3,1998-03-26,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
USW00014894,"WHEELING OHIO CO AIRPORT, WV US",40.16994,-80.64406,364.3,1998-03-27,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
USW00014894,"WHEELING OHIO CO AIRPORT, WV US",40.16994,-80.64406,364.3,1998-03-28,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
USW00014894,"WHEELING OHIO CO AIRPORT, WV US",40.16994,-80.64406,364.3,1998-03-29,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
USW00014894,"WHEELING OHIO CO AIRPORT, WV US",40.16994,-80.64406,364.3,1998-04-01,11.63,",,W",335.0,",,W",334.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
USW00014894,"WHEELING OHIO CO AIRPORT, WV US",40.16994,-80.64406,364.3,2023-05-15,4.92,",,W",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
USW00014894,"WHEELING OHIO CO AIRPORT, WV US",40.16994,-80.64406,364.3,2023-05-16,5.37,",,W",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
USW00014894,"WHEELING OHIO CO AIRPORT, WV US",40.16994,-80.64406,364.3,2023-05-17,8.72,",,W",NaN,NaN,857.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
USW00014894,"WHEELING OHIO CO AIRPORT, WV US",40.16994,-80.64406,364.3,2023-05-18,4.70,",,W",NaN,NaN,2217.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
USW00014894,"WHEELING OHIO CO AIRPORT, WV US",40.16994,-80.64406,364.3,2023-05-19,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
#Solo coger datos con mas de un valor
serie_unico = datos.reset_index().nunique()
columnas_utiles = serie_unico[serie_unico>1].index.tolist()

In [64]:
serie_unico

STATION               1
NAME                  1
LATITUDE              1
LONGITUDE             1
ELEVATION             1
DATE               9176
AWND                 97
AWND_ATTRIBUTES       2
FMTM               1040
FMTM_ATTRIBUTES       2
PGTM               1275
PGTM_ATTRIBUTES       1
PRCP                175
PRCP_ATTRIBUTES       5
PSUN                  1
PSUN_ATTRIBUTES       1
SNOW                  1
SNOW_ATTRIBUTES       1
SNWD                  1
SNWD_ATTRIBUTES       1
TAVG                 79
TAVG_ATTRIBUTES       2
TMAX                 94
TMAX_ATTRIBUTES       6
TMIN                 88
TMIN_ATTRIBUTES       6
TSUN                  1
TSUN_ATTRIBUTES       1
WDF2                 37
WDF2_ATTRIBUTES       2
WDF5                 37
WDF5_ATTRIBUTES       2
WSF2                 45
WSF2_ATTRIBUTES       2
WSF5                 70
WSF5_ATTRIBUTES       2
WT01                  1
WT01_ATTRIBUTES       1
WT02                  1
WT02_ATTRIBUTES       1
WT03                  1
WT03_ATTRIBUTES       1
WT06                  1
WT06_ATTRIBUTES       1
WT08                  1
WT08_ATTRIBUTES       1
WT09                  1
WT09_ATTRIBUTES       1
dtype: int64

In [36]:
df = datos.reset_index()[columnas_utiles].copy()

In [39]:
df.sort_values('DATE')

,DATE,AWND,AWND_ATTRIBUTES,FMTM,FMTM_ATTRIBUTES,PGTM,PRCP,PRCP_ATTRIBUTES,TAVG,TAVG_ATTRIBUTES,...,TMIN,TMIN_ATTRIBUTES,WDF2,WDF2_ATTRIBUTES,WDF5,WDF5_ATTRIBUTES,WSF2,WSF2_ATTRIBUTES,WSF5,WSF5_ATTRIBUTES
0,1998-03-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48.0,",,M",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1998-03-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,64.0,",,M",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1998-03-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,61.0,",,M",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1998-03-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,59.0,",,M",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1998-04-01,11.63,",,W",335.0,",,W",334.0,0.23,",,W,2400",61.0,",,W",...,50.0,",,W",250.0,",,W",250.0,",,W",29.1,",,W",36.0,",,W"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9171,2023-05-15,4.92,",,W",NaN,NaN,NaN,0.00,",,W,2400",NaN,NaN,...,53.0,",,W",320.0,",,W",320.0,",,W",12.1,",,W",14.1,",,W"
9172,2023-05-16,5.37,",,W",NaN,NaN,NaN,0.00,"T,,W,2400",NaN,NaN,...,49.0,",,W",230.0,",,W",240.0,",,W",18.1,",,W",23.9,",,W"
9173,2023-05-17,8.72,",,W",NaN,NaN,857.0,0.00,",,W,2400",NaN,NaN,...,44.0,",,W",340.0,",,W",350.0,",,W",17.0,",,W",21.0,",,W"
9174,2023-05-18,4.70,",,W",NaN,NaN,2217.0,0.00,",,W,2400",NaN,NaN,...,37.0,",,W",120.0,",,W",130.0,",,W",12.1,",,W",16.1,",,W"
9175,2023-05-19,NaN,NaN,NaN,NaN,NaN,0.11,",,D,2400",NaN,NaN,...,59.0,",,D",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [52]:
df_train = df.loc[:"2022"]
df_validacion = df.loc["2022":]

In [59]:
print(f" filas total {df.shape[0]} \n filas train {df_train.shape[0]} \n filas validacion {df_validacion.shape[0]}")

 filas total 9176
 filas train 8672
 filas validacion 504

### Extraer y reservar el dataset de validaci√≥n

In [61]:
raiz

'C:/proyectos/weather_ohio/'

In [62]:
nombre_fichero_validacion = 'validacion.csv'

ruta_completa = raiz + '/02_Datos/02_Validacion/' + nombre_fichero_validacion

df_validacion.to_csv(ruta_completa)

### Extraer y guardar el dataset de trabajo

In [63]:
nombre_fichero_trabajo = 'trabajo.csv'

ruta_completa = raiz + '/02_Datos/03_Trabajo/' + nombre_fichero_trabajo

df_train.to_csv(ruta_completa)